services:
 - type: web
   name: node-redis-api
   env: node
   repo: https://github.com/velizarn/heroku-redis-api.git
   region: frankfurt
   plan: starter
   branch: main
   numInstances: 1
   startCommand: node --optimize_for_size --max_old_space_size=460 --gc_interval=100 ./src/start.js
   envVars:
    - key: REDIS_URL
      sync: false
    - key: WHITELIST_IP
      sync: false